# Generated by Django 5.0.3 on 2024-03-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='应用状态')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'ordering': ['pub_date'],
                'unique_together': {('name', 'is_active')},
                'index_together': {('name', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='标签')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='应用状态')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['pub_date'],
                'unique_together': {('name', 'is_active')},
                'index_together': {('name', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_published', models.BooleanField(choices=[(True, '已发表'), (False, '未发表')], default=False, verbose_name='发表状态')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.category', verbose_name='分类')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.label', verbose_name='标签')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'article',
                'ordering': ['-pub_date'],
                'index_together': {('author', 'category'), ('author', 'label'), ('title', 'author')},
            },
        ),
    ]
