# Generated by Django 5.0.3 on 2024-03-20 09:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pub_date'], 'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-pub_date'], 'verbose_name': 'label', 'verbose_name_plural': 'label'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
