# Generated by Django 5.0.3 on 2024-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='访问IP')),
                ('browser', models.CharField(blank=True, max_length=200, null=True, verbose_name='浏览器')),
            ],
            options={
                'verbose_name': '访问信息',
                'verbose_name_plural': '访问信息',
                'db_table': 'blogs_visit',
                'ordering': ['-visit_time'],
            },
        ),
    ]
